services:
  Braveridge-Manager-gui:
    image: githubyumao/mcsmanager-web:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/Sisko/DS9/Braveridge/web/data:/opt/mcsmanager/web/data
      - /home/Sisko/DS9/Braveridge/web/logs:/opt/mcsmanager/web/logs
    ports:
      - '127.0.0.1:23333:23333'
    networks:
      - proxy

  Braveridge-Manager-daemon:
    image: githubyumao/mcsmanager-daemon:latest
    restart: unless-stopped
    environment:
      - MCSM_DOCKER_WORKSPACE_PATH=/home/Sisko/Braveridge/daemon/data/InstanceData
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/Sisko/DS9/Braveridge/daemon/data:/opt/mcsmanager/daemon/data
      - /home/Sisko/DS9/Braveridge/daemon/logs:/opt/mcsmanager/daemon/logs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '127.0.0.1:24444:24444'

  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
    networks:
      - proxy
    ports:
      - '127.0.0.1:25565:25565'
    volumes:
      # attach the relative directory 'data' to the container's /data path (unsure if configured correctly, TBB)
      - /home/Sisko/DS9/Braveridge/data:/data
      
networks:
  proxy:
    external: true
