services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - proxy
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "Quark"
      DB_MYSQL_PASSWORD: "Wearegr0ss"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'    
    networks:
      - proxy
    environment:
      MYSQL_ROOT_PASSWORD: 'Wearegr0ss'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'Quark'
      MYSQL_PASSWORD: 'Wearegr0ss'
    volumes:
      - ./mysql:/var/lib/mysql
      
networks:
  proxy:
    external: true
